# Configuration file
# Change to debug, assign a different qhull path, or run the python version for the voronoi calculation 
[qhull_path]
bin = /home/cuixi/miniforge3/envs/int_iScore/bin/
[qvoronoi_path]
qvoronoi_bin = /home/cuixi/miniforge3/envs/int_iScore/bin/
executable_name = qvoronoi Fi
debug_qvoronoi = yes
run_python_version = no  
# Fi   - separating hyperplanes for bounded Voronoi region
